#!/bin/bash
# Set the values of WATER and STIR
WATER="water"
STIR="stir."
# Perform the calculations
result=$((5#$(echo "$WATER" | tr "water" "01234") + 5#$(echo "$STIR" | tr "stir." "01234")))
# Translate the result to characters
final_result=$(printf "%o" "$result" | tr "01234567" "bestchol")
# Print the final result
echo "$final_result"
